# Generated by Django 4.2.3 on 2023-07-24 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0002_alter_profile_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
    ]
