# Generated by Django 4.2.3 on 2023-07-24 20:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_media_app", "0003_remove_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="media_attachments",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="avatar",
        ),
    ]
